name: CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  flutter_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3


      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'


      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Flutter SDK
        run: flutter pub get

      - name: Setup Flutter SDK
        run: flutter analyze
        
      - name: Setup Flutter SDK
        run: flutter test

      - name: Setup Flutter SDK
        run: flutter format --dry-run --set-exit-if-changed lib/

      - name: Setup Flutter SDK
        run: flutter format --dry-run --set-exit-if-changed test/

      - name: Setup Flutter SDK
        run: flutter test -- coverage

      - name: Setup Flutter SDK
        run: flutter test --machine > test-results.json

      - name: test-results  
        uses: dorny/test-reporter@v1.4.2
        with:
          path: test-results.json
          reporter: flutter-json

      - name: test-coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 00

 


