name: CI
on:
  push:
    branches:
      - develop
      - master
  pull

jobs:
  flutter_tests:
  runs-on: windows-latest
  steps:
    - name: Get Repository
      uses: actions/checkout@v3


    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'


    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Run Flutter Pub Get
      run: flutter pub get

    - name: Run Flutter tests
      run: flutter test
 


